### PR TITLE
Create an example client SDK usage of retrieving contracts.

### PR DESCRIPTION
**Pull request by taromurao**

### CODE REVIEW

**Comment by joshbwlng** [comment]
@taromurao Can you move this to be a part of the readme? I'd like this to be a part of the deployed docs: https://product-os.github.io/jellyfish-client-sdk/

**Comment by taromurao** [comment]
@joshbwlng I moved the example code to `README.md`. When this PR is merged, I will create a link to this documentation in `README.md` of the main jellyfish repository.

**Comment by joshbwlng** [comment]
@taromurao Looking good. :+1: You'll need to squash the commits and add `Change-type: patch` to your commit message to make VersionBot happy.

**Comment by taromurao** [comment]
@balena-ci I self-certify!

**Comment by taromurao** [comment]
@joshbwlng Thanks for your feedback. The branch has been merged.

**Pull request merged**
