### PR TITLE
Drop link constraints

### PR DESCRIPTION
**Pull request by joshbwlng**
Remove link constraints as we now perform backend relationship
validation and no longer need to in the sdk.

Change-type: major
Signed-off-by: Josh Bowling <josh@balena.io>

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by joshbwlng** [comment]
@balena-ci rebase

**Comment by joshbwlng** [comment]
@balena-ci I self certify!

**Pull request merged**
